### ISSUE TITLE
Azure Pipelines CI should Build Example Cross-Platform

### ISSUE THREAD

**Issue by nibanks** [microsoft/CLOG#21]
Right now, there's a single stage to build clog and then the example, and it all runs on Ubuntu. Let's make building clog a separate stage (Ubuntu is still fine), it publish build artifacts for everything, and then we run the cmake builds in separate stages for each supported platform, ideally Ubuntu, Linux and macOS.

**Comment by ThadHouse** [comment]
I'll do that once #19 is merged. I have a few other things I want to do once that is in as well. And then we can probably build a new release.
